version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:dev
    ports:
      - 8080:8080
    volumes:
      - ./Blog:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
